/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestEURCV } from './TestEURCV.js';
export * as factories from './factories/index.js';
export { TestEURCV__factory } from './factories/TestEURCV__factory.js';